### ISSUE TITLE
Share Button go to playstore

### ISSUE THREAD

**Issue by Rpz75** [Snapchat/creative-kit-sample#44]
After upgrade all app, the share Button dont send a Snapchat... Share Button go to playstore... You have a solution?

**Comment by ramanpreetSinghKhinda** [comment]
Assuming this is for `Android`.

This is most probably because of [Package visibility changes in Android 11](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9).

If your app targets Android 11 (API level 30) or higher, you will need to include the following package query in your app's AndroidManifest.xml:

```
<queries>
  <package android:name="com.snapchat.android" />
</queries>
```

[refer docs](https://kit.snapchat.com/docs/login-kit-react-native)

**Comment by Rpz75** [comment]
it's work, thanks
